---
- hosts: ec2
  become: yes
  tasks:
    - name: Atualizar pacotes
      yum:
        name: "*"
        state: latest

    - name: Instalar pacotes básicos
      yum:
        name:
          - docker
          - python3-pip
        state: present

    - name: Configurar e popular DynamoDB
      hosts: ec2
      become: yes
      vars_files:
        - .env
    
      tasks:
        - name: Instalar AWS CLI
          ansible.builtin.yum:
            name: awscli
            state: present
    
        - name: Criar diretório de dumps
          file:
            path: /home/ec2-user/dumps
            state: directory
    
        - name: Copiar dumps existentes para EC2
          copy:
            src: "./dumps/"
            dest: "/home/ec2-user/dumps/"
            mode: '0644'
    
        - name: Importar dumps disponíveis no DynamoDB
          shell: |
            for dump in /home/ec2-user/dumps/*.json; do
              table=$(basename "$dump" _dump.json)
              echo "Importando $dump na tabela $table..."
              aws dynamodb batch-write-item \
                --request-items file://"$dump" \
                --region us-east-1 || true
            done

    - name: Instalar módulo Docker do Python
      pip:
        name: docker
        executable: pip3
        extra_args: "--ignore-installed"

    - name: Habilitar e iniciar o serviço Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório do projeto
      file:
        path: /opt/app
        state: directory

    - name: Copiar Dockerfile e código da aplicação
      copy:
        src: "{{ playbook_dir }}/../app/"
        dest: /opt/app/
        owner: root
        group: root
        mode: 0755

    - name: Copiar o arquivo .env para o diretório da aplicação
      copy:
        src: "{{ playbook_dir }}/.env"
        dest: /opt/app
        owner: root
        group: root
        mode: 0755


    - name: Build da imagem Docker
      community.docker.docker_image:
        name: bypass-transformer
        build:
          path: /opt/app
        source: build

    - name: Rodar o container
      community.docker.docker_container:
        name: bypass-transformer-container
        image: bypass-transformer
        state: started
        recreate: true
        ports:
          - "5000:5000"
