---
- hosts: ec2
  become: yes
  vars_files:
    - .env

  tasks:
    - name: Instalar AWS CLI
      ansible.builtin.yum:
        name: awscli
        state: present

    - name: Criar diretório de dumps
      ansible.builtin.file:
        path: /home/ec2-user/dumps
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copiar dumps existentes para EC2
      ansible.builtin.synchronize:
        src: "./dumps/"
        dest: "/home/ec2-user/dumps/"
        mode: push
        recursive: yes
      delegate_to: localhost

    - name: Importar dumps disponíveis no DynamoDB
      ansible.builtin.shell: |
        for dump in /home/ec2-user/dumps/*.json; do
          table=$(basename "$dump" _dump.json)
          echo "Importando $dump na tabela $table..."
          aws dynamodb batch-write-item \
            --request-items file://"$dump" \
            --region us-east-1
        done
      args:
        executable: /bin/bash

